// _solid_frontend/src/components/header.tsx
import { Show, Component } from "solid-js";
import { css } from "@emotion/css";
import { useStore } from "../store";
import UserIcon from "./user-icon";

const Header: Component = () => {
  const { state } = useStore();

  const headerStyles = css`
    position: absolute;
    top: 0;
    height: 52px;
    width: 100%;
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 0 8px;
    background-color: #fff;
    border-bottom: 4px solid #0a1931;
  `;

  const titleStyles = css`
    margin: 0;
    color: #0a1931;
  `;

  return (
    <header class={headerStyles}>
      <a href="/">
        <h1 class={titleStyles}>Brackets</h1>
      </a>
      <Show when={state.isConnected}>
        <UserIcon userAddress={state.user} />
      </Show>
    </header>
  );
};

export default Header;

// src/components/header.svelte
<script lang="ts">
  import Logo from "./logo.svelte";
  import UserIcon from "./user-icon.svelte";
</script>

<header>
  <div class="container">
    <div class="left">
      <a href="/"><Logo /></a>
    </div>
    <div class="right">
      <a href="#/dashboard">
        <UserIcon />
      </a>
    </div>
  </div>
</header>

<style>
  header {
    height: 52px;
    background-color: #fff;
    color: #333;
  }

  .container {
    display: flex;
    height: 100%;
    width: 100%;
    max-width: 1024px;
    margin: 0 auto;
    padding: 0 24px;
  }

  .left,
  .right {
    display: flex;
    height: 100%;
    align-items: center;
  }

  .left > a,
  .right > a {
    display: flex;
    align-items: center;
  }

  .left > a > :global(svg) {
    height: 32px;
    width: auto;
  }

  .right {
    margin-left: auto;
  }
</style>
